development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: organi_development
  pool: 5
  username: root
  
  password: robladillo
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: organi_test
  pool: 5
  username: root
  password: robladillo
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: organi_production
  pool: 5
  username: root
  password: robladillo
  host: 127.0.0.1

